//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestion_cabinet_notarial.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banque_pret
    {
        public int Idpret { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<double> Montant { get; set; }
        public Nullable<int> DERU { get; set; }
        public Nullable<int> idcontrat { get; set; }
        public Nullable<int> idbanque { get; set; }
        public Nullable<int> idClient { get; set; }
        public string utilisateur { get; set; }
        public Nullable<double> INTIERET { get; set; }
        public Nullable<double> PAYE_PAR_MOIS { get; set; }
    
        public virtual banque banque { get; set; }
        public virtual client client { get; set; }
        public virtual contrat contrat { get; set; }
        public virtual utilisateur utilisateur1 { get; set; }
    }
}
