//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestion_cabinet_notarial.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CDG
    {
        public int idversement { get; set; }
        public string type { get; set; }
        public Nullable<double> Montant { get; set; }
        public Nullable<double> TPI { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string utilisateur { get; set; }
        public string numdossier { get; set; }
    
        public virtual utilisateur utilisateur1 { get; set; }
        public virtual dossier dossier { get; set; }
    }
}
