//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestion_cabinet_notarial.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientProfessionnel
    {
        public int idClient { get; set; }
        public string ICE { get; set; }
        public string IdentifiantFiscale { get; set; }
    
        public virtual client client { get; set; }
    }
}
