//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestion_cabinet_notarial.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class contrat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public contrat()
        {
            this.Banque_pret = new HashSet<Banque_pret>();
            this.CDGs = new HashSet<CDG>();
            this.credits = new HashSet<credit>();
            this.factures = new HashSet<facture>();
            this.fichiers_contrat = new HashSet<fichiers_contrat>();
            this.payements = new HashSet<payement>();
            this.Signatures = new HashSet<Signature>();
        }
    
        public int Idcontrat { get; set; }
        public string typecontrat { get; set; }
        public Nullable<double> Enregistrement { get; set; }
        public Nullable<double> Ancfcc { get; set; }
        public Nullable<double> Timbres { get; set; }
        public Nullable<double> Honoraires { get; set; }
        public Nullable<double> TVA_Honoraires { get; set; }
        public Nullable<System.DateTime> dateouverture { get; set; }
        public Nullable<System.DateTime> Datefermeture { get; set; }
        public string utilisateur { get; set; }
        public string numdossier { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Banque_pret> Banque_pret { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CDG> CDGs { get; set; }
        public virtual dossier dossier { get; set; }
        public virtual utilisateur utilisateur1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<credit> credits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<facture> factures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fichiers_contrat> fichiers_contrat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payement> payements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Signature> Signatures { get; set; }
    }
}
