//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestion_cabinet_notarial.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class contratcredit
    {
        public int id { get; set; }
        public Nullable<double> montant { get; set; }
        public Nullable<int> idcontrat { get; set; }
        public Nullable<int> deru { get; set; }
        public string descreption { get; set; }
        public string utilisateur { get; set; }
    
        public virtual contrat contrat { get; set; }
        public virtual utilisateur utilisateur1 { get; set; }
    }
}
