//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestion_cabinet_notarial.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class devi
    {
        public int Iddevis { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> Enregistrement { get; set; }
        public Nullable<double> Ancfcc { get; set; }
        public Nullable<double> Timbres { get; set; }
        public Nullable<double> Honoraires { get; set; }
        public Nullable<double> TVA_Honoraires { get; set; }
        public string Objet { get; set; }
        public string typecontrat { get; set; }
        public Nullable<int> idClient { get; set; }
        public string utilisateur { get; set; }
    
        public virtual client client { get; set; }
        public virtual utilisateur utilisateur1 { get; set; }
    }
}
