//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestion_cabinet_notarial.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class dossier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dossier()
        {
            this.contrats = new HashSet<contrat>();
            this.fichiers_dossier = new HashSet<fichiers_dossier>();
            this.partes = new HashSet<parte>();
        }
    
        public string Numdossier { get; set; }
        public string Titrefoncier { get; set; }
        public Nullable<double> PRIX_ACQUISITION { get; set; }
        public string Objet { get; set; }
        public Nullable<System.DateTime> dateouverture { get; set; }
        public Nullable<System.DateTime> Datefermeture { get; set; }
        public Nullable<int> Status { get; set; }
        public string utilisateur { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contrat> contrats { get; set; }
        public virtual utilisateur utilisateur1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fichiers_dossier> fichiers_dossier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<parte> partes { get; set; }
    }
}
