//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestion_cabinet_notarial.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class facture
    {
        public int idfacture { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> idcontrat { get; set; }
        public Nullable<int> idClient { get; set; }
        public string utilisateur { get; set; }
    
        public virtual client client { get; set; }
        public virtual contrat contrat { get; set; }
        public virtual utilisateur utilisateur1 { get; set; }
    }
}
