//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestion_cabinet_notarial.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class fichiers_dossier
    {
        public int idfile { get; set; }
        public string titre { get; set; }
        public string descreption { get; set; }
        public string numdossier { get; set; }
        public string utilisateur { get; set; }
        public string path { get; set; }
    
        public virtual dossier dossier { get; set; }
        public virtual utilisateur utilisateur1 { get; set; }
    }
}
