//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestion_cabinet_notarial.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class information_cabinet
    {
        public string idcabinet { get; set; }
        public string nomcabinet { get; set; }
        public string tele { get; set; }
        public string fax { get; set; }
        public string localisation { get; set; }
        public string logo { get; set; }
        public string email { get; set; }
        public string setweb { get; set; }
    }
}
