//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestion_cabinet_notarial.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class objet
    {
        public int idobj { get; set; }
        public string libbele { get; set; }
        public string titrefoncier { get; set; }
        public string numdossier { get; set; }
        public Nullable<int> idclient { get; set; }
    
        public virtual dossier dossier { get; set; }
        public virtual client client { get; set; }
    }
}
