//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestion_cabinet_notarial.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class payement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public payement()
        {
            this.recus = new HashSet<recu>();
        }
    
        public int idPayement { get; set; }
        public string type { get; set; }
        public string type_Payement { get; set; }
        public Nullable<double> Montant { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> idcontrat { get; set; }
        public Nullable<int> idClient { get; set; }
        public Nullable<int> idbanque { get; set; }
        public string utilisateur { get; set; }
        public string typecharge { get; set; }
    
        public virtual banque banque { get; set; }
        public virtual client client { get; set; }
        public virtual contrat contrat { get; set; }
        public virtual utilisateur utilisateur1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<recu> recus { get; set; }
    }
}
