//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestion_cabinet_notarial.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Signature
    {
        public int IdSignature { get; set; }
        public Nullable<System.DateTime> DateSignatur { get; set; }
        public Nullable<int> idpatres { get; set; }
        public Nullable<int> idcontrat { get; set; }
    
        public virtual contrat contrat { get; set; }
        public virtual parte parte { get; set; }
    }
}
